export const routes = {
  ANIMALS: {
    INDEX: "/animals",
    ID: (id: number | string) => `/animals/${id}`,
    ID_SESSION_ID: (id: number | string, sessionId: number | string) => `/animals/${id}/session/${sessionId}`,
  },
  ANIMALS_CREATE: "/animals-create",
  ANIMAL_TYPES: "/animal-types",
  ANIMAL_COLORS: "/animal-colors",
  AUTH: {
    LOGIN: "/login",
  },
  SESSIONS: {
    INDEX: "/sessions",
    ID: (id: number | string) => `/sessions/${id}`,
    PREDICT: (id: number | string) => `/sessions/${id}/prediction`,
  },
  BREEDS: "/breeds",
  DISEASE_TYPES: "/disease-types",
  DUNG_COLORS: "/dung-colors",
  EYE_LID: "/eye-lids",
  LEATHER_COVER: "/leather-cover",
  MUCOSA_EXAMS: "/mucosa-exams",
  URINE_COLORS: "/urine-colors",
  VACCINE_TYPES: "/vaccine-types",
  DISTRICTS: "/districts",
  REGIONS: "/regions",
  PROPHYLAXIS: '/prophylaxis',
  VETSTATIONS: "/vetstations",
  FARMERS: "/farmers",
  PROFILE: "/profile",
  VETERINARIANS: "/veterinarians",
  BLOOD_SERUM_TEST: "/blood-serum-tests",
  DISEASES: "/diseases",
  DUNG_TESTS: "/dung-tests",
  GENERAL_BLOOD_TESTS: "/general-blood-tests",
  GENERAL_INSPECTIONS: "/general-inspections",
  INSPECTIONS: "/inspections",
  URINE_TESTS: "/urine-tests",
  VACCINES: "/vaccines",
  STATISTICS: "/statistics",
};
