export const ProphylaxisQueryKeys = {
  PROPHYLAXIS: "PROPHYLAXIS",
  PROPHYLAXIS_SELECT: "PROPHYLAXIS_SELECT",
  PROPHYLAXIS_ITEMS: "PROPHYLAXIS_ITEMS",
  PROPHYLAXIS_ITEMS_SELECT: "PROPHYLAXIS_ITEMS_SELECT",
  PROPHYLAXIS_DETAILS: "PROPHYLAXIS_DETAILS",
  PROPHYLAXIS_DETAILS_SELECT: "PROPHYLAXIS_DETAILS_SELECT",
};
