export const ADDITIONAL_CRUD_QUERY_KEYS = {
  // DUNG
  DUNG_CONSISTENCIES: "DUNG_CONSISTENCIES",
  DUNG_CONSISTENCIES_SELECT: "DUNG_CONSISTENCIES_SELECT",

  DUNG_SMELLS: "DUNG_SMELLS",
  DUNG_SMELLS_SELECT: "DUNG_SMELLS_SELECT",

  DUNG_FORMS: "DUNG_FORMS",
  DUNG_FORMS_SELECT: "DUNG_FORMS_SELECT",

  // URINE
  URINE_CONSISTENCIES: "URINE_CONSISTENCIES",
  URINE_CONSISTENCIES_SELECT: "URINE_CONSISTENCIES_SELECT",

  URINE_SMELLS: "URINE_SMELLS",
  URINE_SMELLS_SELECT: "URINE_SMELLS_SELECT",

  URINE_CLARITIES: "URINE_CLARITIES",
  URINE_CLARITIES_SELECT: "URINE_CLARITIES_SELECT",
};
