export const ADDITIONAL_CRUD_QUERY_KEYS = {
  // DUNG
  DUNG_CONSISTENCIES: "DUNG_CONSISTENCIES",
  DUNG_CONSISTENCIES_SELECT: "DUNG_CONSISTENCIES_SELECT",

  DUNG_SMELLS: "DUNG_SMELLS",
  DUNG_SMELLS_SELECT: "DUNG_SMELLS_SELECT",

  DUNG_FORMS: "DUNG_FORMS",
  DUNG_FORMS_SELECT: "DUNG_FORMS_SELECT",

  // URINE
  URINE_CONSISTENCIES: "URINE_CONSISTENCIES",
  URINE_CONSISTENCIES_SELECT: "URINE_CONSISTENCIES_SELECT",

  URINE_SMELLS: "URINE_SMELLS",
  URINE_SMELLS_SELECT: "URINE_SMELLS_SELECT",

  URINE_CLARITIES: "URINE_CLARITIES",
  URINE_CLARITIES_SELECT: "URINE_CLARITIES_SELECT",

  // STATIC LOOKUPS
  ANIMAL_SEXES: "ANIMAL_SEXES",
  BODY_POSITIONS: "BODY_POSITIONS",
  BODY_TYPES: "BODY_TYPES",
  CONSTITUTIONS: "CONSTITUTIONS",
  DOWN_TYPES: "DOWN_TYPES",
  FEATHER_TYPES: "FEATHER_TYPES",
  HAIR_TYPES: "HAIR_TYPES",
  LYMPH_CONSISTENCIES: "LYMPH_CONSISTENCIES",
  LYMPH_MOBILITIES: "LYMPH_MOBILITIES",
  LYMPH_PAINS: "LYMPH_PAINS",
  LYMPH_SHAPES: "LYMPH_SHAPES",
  LYMPH_SIZES: "LYMPH_SIZES",
  LYMPH_SURFACES: "LYMPH_SURFACES",
  LYMPH_TEMPS: "LYMPH_TEMPS",
  RUMEN_FLUID_STATES: "RUMEN_FLUID_STATES",
  MUCOSA_TYPES: "MUCOSA_TYPES",
  OBESITY_TYPES: "OBESITY_TYPES",
  SKIN_COLORS: "SKIN_COLORS",
  SKIN_ELASTICITIES: "SKIN_ELASTICITIES",
  SKIN_HUMIDITIES: "SKIN_HUMIDITIES",
  SKIN_PAINS: "SKIN_PAINS",
  SKIN_SENSITIVITIES: "SKIN_SENSITIVITIES",
  SKIN_SMELLS: "SKIN_SMELLS",
  SKIN_SURFACES: "SKIN_SURFACES",
  SKIN_TEMPS: "SKIN_TEMPS",
  TEMPERAMENTS: "TEMPERAMENTS",
  WOOL_TYPES: "WOOL_TYPES",
};
